### ISSUE TITLE
1.8.9-0.7.3-alpha crashes dedicated forge server 1.8.9 build 1808 on startup

### ISSUE THREAD

**Issue by kreezxil** [gigaherz/ElementsOfPower#10]
Issue: elements-of-power-1.8.9-0.7.3-alpha crashes dedicated forge server 1.8.9 build 1808 on startup

crash report:
https://gist.github.com/6baff32cfe563c65210a705a2481ab25

fml server latest:
https://gist.github.com/ac10bd8d99892b94a227de039abf9e44

**Comment by gigaherz** [comment]
Hello, would it be possible for you to find a smaller pack that still causes the issue? I understand if you can't narrow it down to a single mod, but it would be way too much effort for me to have to download and sort through so many mods in order to track down a small set of mods that I can load in my development environment.

**Comment by Xilef11** [comment]
I got a similar crash (happens in postinit I think) on 0.7.6-alpha on Forge 1.9-12.16.1.1981
log: [http://pastebin.com/Pbn2gqqU](url)
~~I have narrowed down the mods that are in common between both crashes (there is still about 50 of them though): [http://pastebin.com/CZyARie2](url)~~
Actually, it runs fine with those 50 mods... I did some more testing, and it turns out the problem in my case is Quark-beta-18 [http://minecraft.curseforge.com/projects/quark](url)

**Comment by gigaherz** [comment]
Ugh ... I added protection against recipes with invalid OUTPUT stacks, but I never thought of also checking the inputs. Doing so avoids the crash with Quark.

**Comment by gigaherz** [comment]
0.7.7 is up for 1.9, and should avoid the crash. I'll backport the workaround to 1.8.9 later (but not the new stuff -- development will continue in 1.9 only).

**Comment by gigaherz** [comment]
0.7.6b is up for 1.8.9, which backports the workaround.
