### ISSUE TITLE
Element of power Crash 

### ISSUE THREAD

**Issue by ghost** [gigaherz/ElementsOfPower#8]
This is version 0.6.0-alpha, when loading an execption is caugth in element of power causing this crash http://paste.ee/p/vs7Tq

**Comment by gigaherz** [comment]
```
[18:52:58] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[18:52:58] [Client thread/ERROR] [FML]: Caught exception from elementsofpower
java.lang.NullPointerException
[18:52:58] [Client thread/INFO] [STDOUT]: [net.minecraft.crash.CrashReport:func_85057_a:290]: Negative index in crash report handler (0/16)
```

This is... I don't even... IT ERRORED TRYING TO CRASH?!

I have no idea how to debug this. :/

**Comment by gigaherz** [comment]
You seem to have two mods that have the same coremod in them:
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)

Could you try to remove one (or both) of those mods and see if the init crash still happens?

**Comment by ghost** [comment]
This is a bug ,i only have one of the files. and yes it will still crash XD

**Comment by gigaherz** [comment]
I'm not saying it's not a bug. It IS a bug -- somewhere. I just don't know what casues the crash reporting tool to ALSO error. If the crash gave a proper stack trace, I'd be able to see what the cause may be, but I can't really trust that it is indeed my fault, when the crash reporter can't even display a stack trace.

Since this first check didn't change anything, my next step will be to painstakingly download every one of the mods in your list, and see if I can reproduce locally.

**Comment by ghost** [comment]
Also i really never understood with element of power , how do you cast a spell is there a special combo or ?

**Comment by gigaherz** [comment]
Yes it's a bit like magicka. If you do fire, fire explodes around you. If you do water, you throw a ball of water. if you combine Fire+Fire+Water, you do a ball of fire, etc.

**Comment by gigaherz** [comment]
Hey, I haven't had a chance to try replicating your issue yet. Someone suggested to me you could try adding `-XX:-OmitStackTraceInFastThrow` on the java args to be able to produce the needed details on the crash message.

**Comment by ghost** [comment]
i will

**Comment by ghost** [comment]
it doesn't seem to do it anymore.... oh well
